// Code generated by ent, DO NOT EDIT.

package accountnodehealth

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountnodehealth type in the database.
	Label = "account_node_health"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldWindowOpenedAt holds the string denoting the window_opened_at field in the database.
	FieldWindowOpenedAt = "window_opened_at"
	// FieldDegradedAt holds the string denoting the degraded_at field in the database.
	FieldDegradedAt = "degraded_at"
	// FieldCooldownUntil holds the string denoting the cooldown_until field in the database.
	FieldCooldownUntil = "cooldown_until"
	// FieldProbeCount holds the string denoting the probe_count field in the database.
	FieldProbeCount = "probe_count"
	// FieldLastProbeAt holds the string denoting the last_probe_at field in the database.
	FieldLastProbeAt = "last_probe_at"
	// FieldLastProbeAnswer holds the string denoting the last_probe_answer field in the database.
	FieldLastProbeAnswer = "last_probe_answer"
	// Table holds the table name of the accountnodehealth in the database.
	Table = "account_node_health"
)

// Columns holds all SQL columns for accountnodehealth fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldProxyID,
	FieldRegion,
	FieldState,
	FieldWindowOpenedAt,
	FieldDegradedAt,
	FieldCooldownUntil,
	FieldProbeCount,
	FieldLastProbeAt,
	FieldLastProbeAnswer,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultProxyID holds the default value on creation for the "proxy_id" field.
	DefaultProxyID int64
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// RegionValidator is a validator for the "region" field. It is called by the builders before save.
	RegionValidator func(string) error
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// StateValidator is a validator for the "state" field. It is called by the builders before save.
	StateValidator func(string) error
	// DefaultProbeCount holds the default value on creation for the "probe_count" field.
	DefaultProbeCount int64
	// DefaultLastProbeAnswer holds the default value on creation for the "last_probe_answer" field.
	DefaultLastProbeAnswer string
)

// OrderOption defines the ordering options for the AccountNodeHealth queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByWindowOpenedAt orders the results by the window_opened_at field.
func ByWindowOpenedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowOpenedAt, opts...).ToFunc()
}

// ByDegradedAt orders the results by the degraded_at field.
func ByDegradedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDegradedAt, opts...).ToFunc()
}

// ByCooldownUntil orders the results by the cooldown_until field.
func ByCooldownUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownUntil, opts...).ToFunc()
}

// ByProbeCount orders the results by the probe_count field.
func ByProbeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeCount, opts...).ToFunc()
}

// ByLastProbeAt orders the results by the last_probe_at field.
func ByLastProbeAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbeAt, opts...).ToFunc()
}

// ByLastProbeAnswer orders the results by the last_probe_answer field.
func ByLastProbeAnswer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbeAnswer, opts...).ToFunc()
}
