// Code generated by ent, DO NOT EDIT.

package accountnodehealth

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldAccountID, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldProxyID, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldRegion, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldState, v))
}

// WindowOpenedAt applies equality check predicate on the "window_opened_at" field. It's identical to WindowOpenedAtEQ.
func WindowOpenedAt(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldWindowOpenedAt, v))
}

// DegradedAt applies equality check predicate on the "degraded_at" field. It's identical to DegradedAtEQ.
func DegradedAt(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldDegradedAt, v))
}

// CooldownUntil applies equality check predicate on the "cooldown_until" field. It's identical to CooldownUntilEQ.
func CooldownUntil(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldCooldownUntil, v))
}

// ProbeCount applies equality check predicate on the "probe_count" field. It's identical to ProbeCountEQ.
func ProbeCount(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldProbeCount, v))
}

// LastProbeAt applies equality check predicate on the "last_probe_at" field. It's identical to LastProbeAtEQ.
func LastProbeAt(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeAnswer applies equality check predicate on the "last_probe_answer" field. It's identical to LastProbeAnswerEQ.
func LastProbeAnswer(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldLastProbeAnswer, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldAccountID, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDGT applies the GT predicate on the "proxy_id" field.
func ProxyIDGT(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldProxyID, v))
}

// ProxyIDGTE applies the GTE predicate on the "proxy_id" field.
func ProxyIDGTE(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldProxyID, v))
}

// ProxyIDLT applies the LT predicate on the "proxy_id" field.
func ProxyIDLT(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldProxyID, v))
}

// ProxyIDLTE applies the LTE predicate on the "proxy_id" field.
func ProxyIDLTE(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldProxyID, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldContainsFold(FieldRegion, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldContainsFold(FieldState, v))
}

// WindowOpenedAtEQ applies the EQ predicate on the "window_opened_at" field.
func WindowOpenedAtEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldWindowOpenedAt, v))
}

// WindowOpenedAtNEQ applies the NEQ predicate on the "window_opened_at" field.
func WindowOpenedAtNEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldWindowOpenedAt, v))
}

// WindowOpenedAtIn applies the In predicate on the "window_opened_at" field.
func WindowOpenedAtIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldWindowOpenedAt, vs...))
}

// WindowOpenedAtNotIn applies the NotIn predicate on the "window_opened_at" field.
func WindowOpenedAtNotIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldWindowOpenedAt, vs...))
}

// WindowOpenedAtGT applies the GT predicate on the "window_opened_at" field.
func WindowOpenedAtGT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldWindowOpenedAt, v))
}

// WindowOpenedAtGTE applies the GTE predicate on the "window_opened_at" field.
func WindowOpenedAtGTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldWindowOpenedAt, v))
}

// WindowOpenedAtLT applies the LT predicate on the "window_opened_at" field.
func WindowOpenedAtLT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldWindowOpenedAt, v))
}

// WindowOpenedAtLTE applies the LTE predicate on the "window_opened_at" field.
func WindowOpenedAtLTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldWindowOpenedAt, v))
}

// WindowOpenedAtIsNil applies the IsNil predicate on the "window_opened_at" field.
func WindowOpenedAtIsNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIsNull(FieldWindowOpenedAt))
}

// WindowOpenedAtNotNil applies the NotNil predicate on the "window_opened_at" field.
func WindowOpenedAtNotNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotNull(FieldWindowOpenedAt))
}

// DegradedAtEQ applies the EQ predicate on the "degraded_at" field.
func DegradedAtEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldDegradedAt, v))
}

// DegradedAtNEQ applies the NEQ predicate on the "degraded_at" field.
func DegradedAtNEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldDegradedAt, v))
}

// DegradedAtIn applies the In predicate on the "degraded_at" field.
func DegradedAtIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldDegradedAt, vs...))
}

// DegradedAtNotIn applies the NotIn predicate on the "degraded_at" field.
func DegradedAtNotIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldDegradedAt, vs...))
}

// DegradedAtGT applies the GT predicate on the "degraded_at" field.
func DegradedAtGT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldDegradedAt, v))
}

// DegradedAtGTE applies the GTE predicate on the "degraded_at" field.
func DegradedAtGTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldDegradedAt, v))
}

// DegradedAtLT applies the LT predicate on the "degraded_at" field.
func DegradedAtLT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldDegradedAt, v))
}

// DegradedAtLTE applies the LTE predicate on the "degraded_at" field.
func DegradedAtLTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldDegradedAt, v))
}

// DegradedAtIsNil applies the IsNil predicate on the "degraded_at" field.
func DegradedAtIsNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIsNull(FieldDegradedAt))
}

// DegradedAtNotNil applies the NotNil predicate on the "degraded_at" field.
func DegradedAtNotNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotNull(FieldDegradedAt))
}

// CooldownUntilEQ applies the EQ predicate on the "cooldown_until" field.
func CooldownUntilEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldCooldownUntil, v))
}

// CooldownUntilNEQ applies the NEQ predicate on the "cooldown_until" field.
func CooldownUntilNEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldCooldownUntil, v))
}

// CooldownUntilIn applies the In predicate on the "cooldown_until" field.
func CooldownUntilIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldCooldownUntil, vs...))
}

// CooldownUntilNotIn applies the NotIn predicate on the "cooldown_until" field.
func CooldownUntilNotIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldCooldownUntil, vs...))
}

// CooldownUntilGT applies the GT predicate on the "cooldown_until" field.
func CooldownUntilGT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldCooldownUntil, v))
}

// CooldownUntilGTE applies the GTE predicate on the "cooldown_until" field.
func CooldownUntilGTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldCooldownUntil, v))
}

// CooldownUntilLT applies the LT predicate on the "cooldown_until" field.
func CooldownUntilLT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldCooldownUntil, v))
}

// CooldownUntilLTE applies the LTE predicate on the "cooldown_until" field.
func CooldownUntilLTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldCooldownUntil, v))
}

// CooldownUntilIsNil applies the IsNil predicate on the "cooldown_until" field.
func CooldownUntilIsNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIsNull(FieldCooldownUntil))
}

// CooldownUntilNotNil applies the NotNil predicate on the "cooldown_until" field.
func CooldownUntilNotNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotNull(FieldCooldownUntil))
}

// ProbeCountEQ applies the EQ predicate on the "probe_count" field.
func ProbeCountEQ(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldProbeCount, v))
}

// ProbeCountNEQ applies the NEQ predicate on the "probe_count" field.
func ProbeCountNEQ(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldProbeCount, v))
}

// ProbeCountIn applies the In predicate on the "probe_count" field.
func ProbeCountIn(vs ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldProbeCount, vs...))
}

// ProbeCountNotIn applies the NotIn predicate on the "probe_count" field.
func ProbeCountNotIn(vs ...int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldProbeCount, vs...))
}

// ProbeCountGT applies the GT predicate on the "probe_count" field.
func ProbeCountGT(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldProbeCount, v))
}

// ProbeCountGTE applies the GTE predicate on the "probe_count" field.
func ProbeCountGTE(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldProbeCount, v))
}

// ProbeCountLT applies the LT predicate on the "probe_count" field.
func ProbeCountLT(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldProbeCount, v))
}

// ProbeCountLTE applies the LTE predicate on the "probe_count" field.
func ProbeCountLTE(v int64) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldProbeCount, v))
}

// LastProbeAtEQ applies the EQ predicate on the "last_probe_at" field.
func LastProbeAtEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldLastProbeAt, v))
}

// LastProbeAtNEQ applies the NEQ predicate on the "last_probe_at" field.
func LastProbeAtNEQ(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldLastProbeAt, v))
}

// LastProbeAtIn applies the In predicate on the "last_probe_at" field.
func LastProbeAtIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldLastProbeAt, vs...))
}

// LastProbeAtNotIn applies the NotIn predicate on the "last_probe_at" field.
func LastProbeAtNotIn(vs ...time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldLastProbeAt, vs...))
}

// LastProbeAtGT applies the GT predicate on the "last_probe_at" field.
func LastProbeAtGT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldLastProbeAt, v))
}

// LastProbeAtGTE applies the GTE predicate on the "last_probe_at" field.
func LastProbeAtGTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldLastProbeAt, v))
}

// LastProbeAtLT applies the LT predicate on the "last_probe_at" field.
func LastProbeAtLT(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldLastProbeAt, v))
}

// LastProbeAtLTE applies the LTE predicate on the "last_probe_at" field.
func LastProbeAtLTE(v time.Time) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldLastProbeAt, v))
}

// LastProbeAtIsNil applies the IsNil predicate on the "last_probe_at" field.
func LastProbeAtIsNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIsNull(FieldLastProbeAt))
}

// LastProbeAtNotNil applies the NotNil predicate on the "last_probe_at" field.
func LastProbeAtNotNil() predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotNull(FieldLastProbeAt))
}

// LastProbeAnswerEQ applies the EQ predicate on the "last_probe_answer" field.
func LastProbeAnswerEQ(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEQ(FieldLastProbeAnswer, v))
}

// LastProbeAnswerNEQ applies the NEQ predicate on the "last_probe_answer" field.
func LastProbeAnswerNEQ(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNEQ(FieldLastProbeAnswer, v))
}

// LastProbeAnswerIn applies the In predicate on the "last_probe_answer" field.
func LastProbeAnswerIn(vs ...string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldIn(FieldLastProbeAnswer, vs...))
}

// LastProbeAnswerNotIn applies the NotIn predicate on the "last_probe_answer" field.
func LastProbeAnswerNotIn(vs ...string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldNotIn(FieldLastProbeAnswer, vs...))
}

// LastProbeAnswerGT applies the GT predicate on the "last_probe_answer" field.
func LastProbeAnswerGT(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGT(FieldLastProbeAnswer, v))
}

// LastProbeAnswerGTE applies the GTE predicate on the "last_probe_answer" field.
func LastProbeAnswerGTE(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldGTE(FieldLastProbeAnswer, v))
}

// LastProbeAnswerLT applies the LT predicate on the "last_probe_answer" field.
func LastProbeAnswerLT(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLT(FieldLastProbeAnswer, v))
}

// LastProbeAnswerLTE applies the LTE predicate on the "last_probe_answer" field.
func LastProbeAnswerLTE(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldLTE(FieldLastProbeAnswer, v))
}

// LastProbeAnswerContains applies the Contains predicate on the "last_probe_answer" field.
func LastProbeAnswerContains(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldContains(FieldLastProbeAnswer, v))
}

// LastProbeAnswerHasPrefix applies the HasPrefix predicate on the "last_probe_answer" field.
func LastProbeAnswerHasPrefix(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldHasPrefix(FieldLastProbeAnswer, v))
}

// LastProbeAnswerHasSuffix applies the HasSuffix predicate on the "last_probe_answer" field.
func LastProbeAnswerHasSuffix(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldHasSuffix(FieldLastProbeAnswer, v))
}

// LastProbeAnswerEqualFold applies the EqualFold predicate on the "last_probe_answer" field.
func LastProbeAnswerEqualFold(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldEqualFold(FieldLastProbeAnswer, v))
}

// LastProbeAnswerContainsFold applies the ContainsFold predicate on the "last_probe_answer" field.
func LastProbeAnswerContainsFold(v string) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.FieldContainsFold(FieldLastProbeAnswer, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountNodeHealth) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountNodeHealth) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountNodeHealth) predicate.AccountNodeHealth {
	return predicate.AccountNodeHealth(sql.NotPredicates(p))
}
