// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountnodehealth"
)

// AccountNodeHealthCreate is the builder for creating a AccountNodeHealth entity.
type AccountNodeHealthCreate struct {
	config
	mutation *AccountNodeHealthMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountNodeHealthCreate) SetCreatedAt(v time.Time) *AccountNodeHealthCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableCreatedAt(v *time.Time) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountNodeHealthCreate) SetUpdatedAt(v time.Time) *AccountNodeHealthCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableUpdatedAt(v *time.Time) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountNodeHealthCreate) SetAccountID(v int64) *AccountNodeHealthCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *AccountNodeHealthCreate) SetProxyID(v int64) *AccountNodeHealthCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableProxyID(v *int64) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetProxyID(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *AccountNodeHealthCreate) SetRegion(v string) *AccountNodeHealthCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableRegion(v *string) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *AccountNodeHealthCreate) SetState(v string) *AccountNodeHealthCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableState(v *string) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetWindowOpenedAt sets the "window_opened_at" field.
func (_c *AccountNodeHealthCreate) SetWindowOpenedAt(v time.Time) *AccountNodeHealthCreate {
	_c.mutation.SetWindowOpenedAt(v)
	return _c
}

// SetNillableWindowOpenedAt sets the "window_opened_at" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableWindowOpenedAt(v *time.Time) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetWindowOpenedAt(*v)
	}
	return _c
}

// SetDegradedAt sets the "degraded_at" field.
func (_c *AccountNodeHealthCreate) SetDegradedAt(v time.Time) *AccountNodeHealthCreate {
	_c.mutation.SetDegradedAt(v)
	return _c
}

// SetNillableDegradedAt sets the "degraded_at" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableDegradedAt(v *time.Time) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetDegradedAt(*v)
	}
	return _c
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_c *AccountNodeHealthCreate) SetCooldownUntil(v time.Time) *AccountNodeHealthCreate {
	_c.mutation.SetCooldownUntil(v)
	return _c
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableCooldownUntil(v *time.Time) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetCooldownUntil(*v)
	}
	return _c
}

// SetProbeCount sets the "probe_count" field.
func (_c *AccountNodeHealthCreate) SetProbeCount(v int64) *AccountNodeHealthCreate {
	_c.mutation.SetProbeCount(v)
	return _c
}

// SetNillableProbeCount sets the "probe_count" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableProbeCount(v *int64) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetProbeCount(*v)
	}
	return _c
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_c *AccountNodeHealthCreate) SetLastProbeAt(v time.Time) *AccountNodeHealthCreate {
	_c.mutation.SetLastProbeAt(v)
	return _c
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableLastProbeAt(v *time.Time) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetLastProbeAt(*v)
	}
	return _c
}

// SetLastProbeAnswer sets the "last_probe_answer" field.
func (_c *AccountNodeHealthCreate) SetLastProbeAnswer(v string) *AccountNodeHealthCreate {
	_c.mutation.SetLastProbeAnswer(v)
	return _c
}

// SetNillableLastProbeAnswer sets the "last_probe_answer" field if the given value is not nil.
func (_c *AccountNodeHealthCreate) SetNillableLastProbeAnswer(v *string) *AccountNodeHealthCreate {
	if v != nil {
		_c.SetLastProbeAnswer(*v)
	}
	return _c
}

// Mutation returns the AccountNodeHealthMutation object of the builder.
func (_c *AccountNodeHealthCreate) Mutation() *AccountNodeHealthMutation {
	return _c.mutation
}

// Save creates the AccountNodeHealth in the database.
func (_c *AccountNodeHealthCreate) Save(ctx context.Context) (*AccountNodeHealth, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountNodeHealthCreate) SaveX(ctx context.Context) *AccountNodeHealth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountNodeHealthCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountNodeHealthCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountNodeHealthCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountnodehealth.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountnodehealth.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ProxyID(); !ok {
		v := accountnodehealth.DefaultProxyID
		_c.mutation.SetProxyID(v)
	}
	if _, ok := _c.mutation.Region(); !ok {
		v := accountnodehealth.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := accountnodehealth.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.ProbeCount(); !ok {
		v := accountnodehealth.DefaultProbeCount
		_c.mutation.SetProbeCount(v)
	}
	if _, ok := _c.mutation.LastProbeAnswer(); !ok {
		v := accountnodehealth.DefaultLastProbeAnswer
		_c.mutation.SetLastProbeAnswer(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountNodeHealthCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountNodeHealth.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountNodeHealth.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountNodeHealth.account_id"`)}
	}
	if _, ok := _c.mutation.ProxyID(); !ok {
		return &ValidationError{Name: "proxy_id", err: errors.New(`ent: missing required field "AccountNodeHealth.proxy_id"`)}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "AccountNodeHealth.region"`)}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := accountnodehealth.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "AccountNodeHealth.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "AccountNodeHealth.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := accountnodehealth.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "AccountNodeHealth.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProbeCount(); !ok {
		return &ValidationError{Name: "probe_count", err: errors.New(`ent: missing required field "AccountNodeHealth.probe_count"`)}
	}
	if _, ok := _c.mutation.LastProbeAnswer(); !ok {
		return &ValidationError{Name: "last_probe_answer", err: errors.New(`ent: missing required field "AccountNodeHealth.last_probe_answer"`)}
	}
	return nil
}

func (_c *AccountNodeHealthCreate) sqlSave(ctx context.Context) (*AccountNodeHealth, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountNodeHealthCreate) createSpec() (*AccountNodeHealth, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountNodeHealth{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountnodehealth.Table, sqlgraph.NewFieldSpec(accountnodehealth.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountnodehealth.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountnodehealth.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountnodehealth.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.ProxyID(); ok {
		_spec.SetField(accountnodehealth.FieldProxyID, field.TypeInt64, value)
		_node.ProxyID = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(accountnodehealth.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(accountnodehealth.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.WindowOpenedAt(); ok {
		_spec.SetField(accountnodehealth.FieldWindowOpenedAt, field.TypeTime, value)
		_node.WindowOpenedAt = &value
	}
	if value, ok := _c.mutation.DegradedAt(); ok {
		_spec.SetField(accountnodehealth.FieldDegradedAt, field.TypeTime, value)
		_node.DegradedAt = &value
	}
	if value, ok := _c.mutation.CooldownUntil(); ok {
		_spec.SetField(accountnodehealth.FieldCooldownUntil, field.TypeTime, value)
		_node.CooldownUntil = &value
	}
	if value, ok := _c.mutation.ProbeCount(); ok {
		_spec.SetField(accountnodehealth.FieldProbeCount, field.TypeInt64, value)
		_node.ProbeCount = value
	}
	if value, ok := _c.mutation.LastProbeAt(); ok {
		_spec.SetField(accountnodehealth.FieldLastProbeAt, field.TypeTime, value)
		_node.LastProbeAt = &value
	}
	if value, ok := _c.mutation.LastProbeAnswer(); ok {
		_spec.SetField(accountnodehealth.FieldLastProbeAnswer, field.TypeString, value)
		_node.LastProbeAnswer = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountNodeHealth.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountNodeHealthUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountNodeHealthCreate) OnConflict(opts ...sql.ConflictOption) *AccountNodeHealthUpsertOne {
	_c.conflict = opts
	return &AccountNodeHealthUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountNodeHealth.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountNodeHealthCreate) OnConflictColumns(columns ...string) *AccountNodeHealthUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountNodeHealthUpsertOne{
		create: _c,
	}
}

type (
	// AccountNodeHealthUpsertOne is the builder for "upsert"-ing
	//  one AccountNodeHealth node.
	AccountNodeHealthUpsertOne struct {
		create *AccountNodeHealthCreate
	}

	// AccountNodeHealthUpsert is the "OnConflict" setter.
	AccountNodeHealthUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountNodeHealthUpsert) SetUpdatedAt(v time.Time) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateUpdatedAt() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountNodeHealthUpsert) SetAccountID(v int64) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateAccountID() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountNodeHealthUpsert) AddAccountID(v int64) *AccountNodeHealthUpsert {
	u.Add(accountnodehealth.FieldAccountID, v)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountNodeHealthUpsert) SetProxyID(v int64) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateProxyID() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldProxyID)
	return u
}

// AddProxyID adds v to the "proxy_id" field.
func (u *AccountNodeHealthUpsert) AddProxyID(v int64) *AccountNodeHealthUpsert {
	u.Add(accountnodehealth.FieldProxyID, v)
	return u
}

// SetRegion sets the "region" field.
func (u *AccountNodeHealthUpsert) SetRegion(v string) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldRegion, v)
	return u
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateRegion() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldRegion)
	return u
}

// SetState sets the "state" field.
func (u *AccountNodeHealthUpsert) SetState(v string) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateState() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldState)
	return u
}

// SetWindowOpenedAt sets the "window_opened_at" field.
func (u *AccountNodeHealthUpsert) SetWindowOpenedAt(v time.Time) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldWindowOpenedAt, v)
	return u
}

// UpdateWindowOpenedAt sets the "window_opened_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateWindowOpenedAt() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldWindowOpenedAt)
	return u
}

// ClearWindowOpenedAt clears the value of the "window_opened_at" field.
func (u *AccountNodeHealthUpsert) ClearWindowOpenedAt() *AccountNodeHealthUpsert {
	u.SetNull(accountnodehealth.FieldWindowOpenedAt)
	return u
}

// SetDegradedAt sets the "degraded_at" field.
func (u *AccountNodeHealthUpsert) SetDegradedAt(v time.Time) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldDegradedAt, v)
	return u
}

// UpdateDegradedAt sets the "degraded_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateDegradedAt() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldDegradedAt)
	return u
}

// ClearDegradedAt clears the value of the "degraded_at" field.
func (u *AccountNodeHealthUpsert) ClearDegradedAt() *AccountNodeHealthUpsert {
	u.SetNull(accountnodehealth.FieldDegradedAt)
	return u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (u *AccountNodeHealthUpsert) SetCooldownUntil(v time.Time) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldCooldownUntil, v)
	return u
}

// UpdateCooldownUntil sets the "cooldown_until" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateCooldownUntil() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldCooldownUntil)
	return u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (u *AccountNodeHealthUpsert) ClearCooldownUntil() *AccountNodeHealthUpsert {
	u.SetNull(accountnodehealth.FieldCooldownUntil)
	return u
}

// SetProbeCount sets the "probe_count" field.
func (u *AccountNodeHealthUpsert) SetProbeCount(v int64) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldProbeCount, v)
	return u
}

// UpdateProbeCount sets the "probe_count" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateProbeCount() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldProbeCount)
	return u
}

// AddProbeCount adds v to the "probe_count" field.
func (u *AccountNodeHealthUpsert) AddProbeCount(v int64) *AccountNodeHealthUpsert {
	u.Add(accountnodehealth.FieldProbeCount, v)
	return u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *AccountNodeHealthUpsert) SetLastProbeAt(v time.Time) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldLastProbeAt, v)
	return u
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateLastProbeAt() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldLastProbeAt)
	return u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *AccountNodeHealthUpsert) ClearLastProbeAt() *AccountNodeHealthUpsert {
	u.SetNull(accountnodehealth.FieldLastProbeAt)
	return u
}

// SetLastProbeAnswer sets the "last_probe_answer" field.
func (u *AccountNodeHealthUpsert) SetLastProbeAnswer(v string) *AccountNodeHealthUpsert {
	u.Set(accountnodehealth.FieldLastProbeAnswer, v)
	return u
}

// UpdateLastProbeAnswer sets the "last_probe_answer" field to the value that was provided on create.
func (u *AccountNodeHealthUpsert) UpdateLastProbeAnswer() *AccountNodeHealthUpsert {
	u.SetExcluded(accountnodehealth.FieldLastProbeAnswer)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountNodeHealth.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountNodeHealthUpsertOne) UpdateNewValues() *AccountNodeHealthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountnodehealth.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountNodeHealth.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountNodeHealthUpsertOne) Ignore() *AccountNodeHealthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountNodeHealthUpsertOne) DoNothing() *AccountNodeHealthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountNodeHealthCreate.OnConflict
// documentation for more info.
func (u *AccountNodeHealthUpsertOne) Update(set func(*AccountNodeHealthUpsert)) *AccountNodeHealthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountNodeHealthUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountNodeHealthUpsertOne) SetUpdatedAt(v time.Time) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateUpdatedAt() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountNodeHealthUpsertOne) SetAccountID(v int64) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountNodeHealthUpsertOne) AddAccountID(v int64) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateAccountID() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountNodeHealthUpsertOne) SetProxyID(v int64) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *AccountNodeHealthUpsertOne) AddProxyID(v int64) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateProxyID() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateProxyID()
	})
}

// SetRegion sets the "region" field.
func (u *AccountNodeHealthUpsertOne) SetRegion(v string) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateRegion() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateRegion()
	})
}

// SetState sets the "state" field.
func (u *AccountNodeHealthUpsertOne) SetState(v string) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateState() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateState()
	})
}

// SetWindowOpenedAt sets the "window_opened_at" field.
func (u *AccountNodeHealthUpsertOne) SetWindowOpenedAt(v time.Time) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetWindowOpenedAt(v)
	})
}

// UpdateWindowOpenedAt sets the "window_opened_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateWindowOpenedAt() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateWindowOpenedAt()
	})
}

// ClearWindowOpenedAt clears the value of the "window_opened_at" field.
func (u *AccountNodeHealthUpsertOne) ClearWindowOpenedAt() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearWindowOpenedAt()
	})
}

// SetDegradedAt sets the "degraded_at" field.
func (u *AccountNodeHealthUpsertOne) SetDegradedAt(v time.Time) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetDegradedAt(v)
	})
}

// UpdateDegradedAt sets the "degraded_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateDegradedAt() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateDegradedAt()
	})
}

// ClearDegradedAt clears the value of the "degraded_at" field.
func (u *AccountNodeHealthUpsertOne) ClearDegradedAt() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearDegradedAt()
	})
}

// SetCooldownUntil sets the "cooldown_until" field.
func (u *AccountNodeHealthUpsertOne) SetCooldownUntil(v time.Time) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetCooldownUntil(v)
	})
}

// UpdateCooldownUntil sets the "cooldown_until" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateCooldownUntil() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateCooldownUntil()
	})
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (u *AccountNodeHealthUpsertOne) ClearCooldownUntil() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearCooldownUntil()
	})
}

// SetProbeCount sets the "probe_count" field.
func (u *AccountNodeHealthUpsertOne) SetProbeCount(v int64) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetProbeCount(v)
	})
}

// AddProbeCount adds v to the "probe_count" field.
func (u *AccountNodeHealthUpsertOne) AddProbeCount(v int64) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.AddProbeCount(v)
	})
}

// UpdateProbeCount sets the "probe_count" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateProbeCount() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateProbeCount()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *AccountNodeHealthUpsertOne) SetLastProbeAt(v time.Time) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateLastProbeAt() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *AccountNodeHealthUpsertOne) ClearLastProbeAt() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetLastProbeAnswer sets the "last_probe_answer" field.
func (u *AccountNodeHealthUpsertOne) SetLastProbeAnswer(v string) *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetLastProbeAnswer(v)
	})
}

// UpdateLastProbeAnswer sets the "last_probe_answer" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertOne) UpdateLastProbeAnswer() *AccountNodeHealthUpsertOne {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateLastProbeAnswer()
	})
}

// Exec executes the query.
func (u *AccountNodeHealthUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountNodeHealthCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountNodeHealthUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountNodeHealthUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountNodeHealthUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountNodeHealthCreateBulk is the builder for creating many AccountNodeHealth entities in bulk.
type AccountNodeHealthCreateBulk struct {
	config
	err      error
	builders []*AccountNodeHealthCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountNodeHealth entities in the database.
func (_c *AccountNodeHealthCreateBulk) Save(ctx context.Context) ([]*AccountNodeHealth, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountNodeHealth, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountNodeHealthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountNodeHealthCreateBulk) SaveX(ctx context.Context) []*AccountNodeHealth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountNodeHealthCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountNodeHealthCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountNodeHealth.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountNodeHealthUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountNodeHealthCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountNodeHealthUpsertBulk {
	_c.conflict = opts
	return &AccountNodeHealthUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountNodeHealth.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountNodeHealthCreateBulk) OnConflictColumns(columns ...string) *AccountNodeHealthUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountNodeHealthUpsertBulk{
		create: _c,
	}
}

// AccountNodeHealthUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountNodeHealth nodes.
type AccountNodeHealthUpsertBulk struct {
	create *AccountNodeHealthCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountNodeHealth.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountNodeHealthUpsertBulk) UpdateNewValues() *AccountNodeHealthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountnodehealth.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountNodeHealth.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountNodeHealthUpsertBulk) Ignore() *AccountNodeHealthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountNodeHealthUpsertBulk) DoNothing() *AccountNodeHealthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountNodeHealthCreateBulk.OnConflict
// documentation for more info.
func (u *AccountNodeHealthUpsertBulk) Update(set func(*AccountNodeHealthUpsert)) *AccountNodeHealthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountNodeHealthUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountNodeHealthUpsertBulk) SetUpdatedAt(v time.Time) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateUpdatedAt() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountNodeHealthUpsertBulk) SetAccountID(v int64) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountNodeHealthUpsertBulk) AddAccountID(v int64) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateAccountID() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateAccountID()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *AccountNodeHealthUpsertBulk) SetProxyID(v int64) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *AccountNodeHealthUpsertBulk) AddProxyID(v int64) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateProxyID() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateProxyID()
	})
}

// SetRegion sets the "region" field.
func (u *AccountNodeHealthUpsertBulk) SetRegion(v string) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateRegion() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateRegion()
	})
}

// SetState sets the "state" field.
func (u *AccountNodeHealthUpsertBulk) SetState(v string) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateState() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateState()
	})
}

// SetWindowOpenedAt sets the "window_opened_at" field.
func (u *AccountNodeHealthUpsertBulk) SetWindowOpenedAt(v time.Time) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetWindowOpenedAt(v)
	})
}

// UpdateWindowOpenedAt sets the "window_opened_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateWindowOpenedAt() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateWindowOpenedAt()
	})
}

// ClearWindowOpenedAt clears the value of the "window_opened_at" field.
func (u *AccountNodeHealthUpsertBulk) ClearWindowOpenedAt() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearWindowOpenedAt()
	})
}

// SetDegradedAt sets the "degraded_at" field.
func (u *AccountNodeHealthUpsertBulk) SetDegradedAt(v time.Time) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetDegradedAt(v)
	})
}

// UpdateDegradedAt sets the "degraded_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateDegradedAt() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateDegradedAt()
	})
}

// ClearDegradedAt clears the value of the "degraded_at" field.
func (u *AccountNodeHealthUpsertBulk) ClearDegradedAt() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearDegradedAt()
	})
}

// SetCooldownUntil sets the "cooldown_until" field.
func (u *AccountNodeHealthUpsertBulk) SetCooldownUntil(v time.Time) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetCooldownUntil(v)
	})
}

// UpdateCooldownUntil sets the "cooldown_until" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateCooldownUntil() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateCooldownUntil()
	})
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (u *AccountNodeHealthUpsertBulk) ClearCooldownUntil() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearCooldownUntil()
	})
}

// SetProbeCount sets the "probe_count" field.
func (u *AccountNodeHealthUpsertBulk) SetProbeCount(v int64) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetProbeCount(v)
	})
}

// AddProbeCount adds v to the "probe_count" field.
func (u *AccountNodeHealthUpsertBulk) AddProbeCount(v int64) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.AddProbeCount(v)
	})
}

// UpdateProbeCount sets the "probe_count" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateProbeCount() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateProbeCount()
	})
}

// SetLastProbeAt sets the "last_probe_at" field.
func (u *AccountNodeHealthUpsertBulk) SetLastProbeAt(v time.Time) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetLastProbeAt(v)
	})
}

// UpdateLastProbeAt sets the "last_probe_at" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateLastProbeAt() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateLastProbeAt()
	})
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (u *AccountNodeHealthUpsertBulk) ClearLastProbeAt() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.ClearLastProbeAt()
	})
}

// SetLastProbeAnswer sets the "last_probe_answer" field.
func (u *AccountNodeHealthUpsertBulk) SetLastProbeAnswer(v string) *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.SetLastProbeAnswer(v)
	})
}

// UpdateLastProbeAnswer sets the "last_probe_answer" field to the value that was provided on create.
func (u *AccountNodeHealthUpsertBulk) UpdateLastProbeAnswer() *AccountNodeHealthUpsertBulk {
	return u.Update(func(s *AccountNodeHealthUpsert) {
		s.UpdateLastProbeAnswer()
	})
}

// Exec executes the query.
func (u *AccountNodeHealthUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountNodeHealthCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountNodeHealthCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountNodeHealthUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
