// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountnodehealth"
)

// AccountNodeHealth is the model entity for the AccountNodeHealth schema.
type AccountNodeHealth struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// 出口代理 ID；0 = 直连出口（无代理）。
	ProxyID int64 `json:"proxy_id,omitempty"`
	// 出口地理快照（国家/区域，尽力填充）。
	Region string `json:"region,omitempty"`
	// unknown | full_power | degraded | cooldown。
	State string `json:"state,omitempty"`
	// 最近一次命中满血的时间（乐观窗口起点）。
	WindowOpenedAt *time.Time `json:"window_opened_at,omitempty"`
	// 最近一次判定降智的时间。
	DegradedAt *time.Time `json:"degraded_at,omitempty"`
	// 降智冷却截止时间；到期前该组合应保持静默。
	CooldownUntil *time.Time `json:"cooldown_until,omitempty"`
	// 累计探测次数（题库轮换依据）。
	ProbeCount int64 `json:"probe_count,omitempty"`
	// 最近一次探测时间（含失败探测；探测即污染）。
	LastProbeAt *time.Time `json:"last_probe_at,omitempty"`
	// 最近一次指纹问题的上游原文回答（截断存储）。
	LastProbeAnswer string `json:"last_probe_answer,omitempty"`
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountNodeHealth) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountnodehealth.FieldID, accountnodehealth.FieldAccountID, accountnodehealth.FieldProxyID, accountnodehealth.FieldProbeCount:
			values[i] = new(sql.NullInt64)
		case accountnodehealth.FieldRegion, accountnodehealth.FieldState, accountnodehealth.FieldLastProbeAnswer:
			values[i] = new(sql.NullString)
		case accountnodehealth.FieldCreatedAt, accountnodehealth.FieldUpdatedAt, accountnodehealth.FieldWindowOpenedAt, accountnodehealth.FieldDegradedAt, accountnodehealth.FieldCooldownUntil, accountnodehealth.FieldLastProbeAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountNodeHealth fields.
func (_m *AccountNodeHealth) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountnodehealth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountnodehealth.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountnodehealth.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountnodehealth.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountnodehealth.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = value.Int64
			}
		case accountnodehealth.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case accountnodehealth.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case accountnodehealth.FieldWindowOpenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_opened_at", values[i])
			} else if value.Valid {
				_m.WindowOpenedAt = new(time.Time)
				*_m.WindowOpenedAt = value.Time
			}
		case accountnodehealth.FieldDegradedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field degraded_at", values[i])
			} else if value.Valid {
				_m.DegradedAt = new(time.Time)
				*_m.DegradedAt = value.Time
			}
		case accountnodehealth.FieldCooldownUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_until", values[i])
			} else if value.Valid {
				_m.CooldownUntil = new(time.Time)
				*_m.CooldownUntil = value.Time
			}
		case accountnodehealth.FieldProbeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probe_count", values[i])
			} else if value.Valid {
				_m.ProbeCount = value.Int64
			}
		case accountnodehealth.FieldLastProbeAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_at", values[i])
			} else if value.Valid {
				_m.LastProbeAt = new(time.Time)
				*_m.LastProbeAt = value.Time
			}
		case accountnodehealth.FieldLastProbeAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_probe_answer", values[i])
			} else if value.Valid {
				_m.LastProbeAnswer = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountNodeHealth.
// This includes values selected through modifiers, order, etc.
func (_m *AccountNodeHealth) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountNodeHealth.
// Note that you need to call AccountNodeHealth.Unwrap() before calling this method if this AccountNodeHealth
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountNodeHealth) Update() *AccountNodeHealthUpdateOne {
	return NewAccountNodeHealthClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountNodeHealth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountNodeHealth) Unwrap() *AccountNodeHealth {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountNodeHealth is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountNodeHealth) String() string {
	var builder strings.Builder
	builder.WriteString("AccountNodeHealth(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("proxy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyID))
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	if v := _m.WindowOpenedAt; v != nil {
		builder.WriteString("window_opened_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DegradedAt; v != nil {
		builder.WriteString("degraded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CooldownUntil; v != nil {
		builder.WriteString("cooldown_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("probe_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProbeCount))
	builder.WriteString(", ")
	if v := _m.LastProbeAt; v != nil {
		builder.WriteString("last_probe_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_probe_answer=")
	builder.WriteString(_m.LastProbeAnswer)
	builder.WriteByte(')')
	return builder.String()
}

// AccountNodeHealths is a parsable slice of AccountNodeHealth.
type AccountNodeHealths []*AccountNodeHealth
