// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountnodehealth"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountNodeHealthDelete is the builder for deleting a AccountNodeHealth entity.
type AccountNodeHealthDelete struct {
	config
	hooks    []Hook
	mutation *AccountNodeHealthMutation
}

// Where appends a list predicates to the AccountNodeHealthDelete builder.
func (_d *AccountNodeHealthDelete) Where(ps ...predicate.AccountNodeHealth) *AccountNodeHealthDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountNodeHealthDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountNodeHealthDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountNodeHealthDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountnodehealth.Table, sqlgraph.NewFieldSpec(accountnodehealth.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountNodeHealthDeleteOne is the builder for deleting a single AccountNodeHealth entity.
type AccountNodeHealthDeleteOne struct {
	_d *AccountNodeHealthDelete
}

// Where appends a list predicates to the AccountNodeHealthDelete builder.
func (_d *AccountNodeHealthDeleteOne) Where(ps ...predicate.AccountNodeHealth) *AccountNodeHealthDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountNodeHealthDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountnodehealth.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountNodeHealthDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
