// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountnodehealth"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountNodeHealthUpdate is the builder for updating AccountNodeHealth entities.
type AccountNodeHealthUpdate struct {
	config
	hooks    []Hook
	mutation *AccountNodeHealthMutation
}

// Where appends a list predicates to the AccountNodeHealthUpdate builder.
func (_u *AccountNodeHealthUpdate) Where(ps ...predicate.AccountNodeHealth) *AccountNodeHealthUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountNodeHealthUpdate) SetUpdatedAt(v time.Time) *AccountNodeHealthUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountNodeHealthUpdate) SetAccountID(v int64) *AccountNodeHealthUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableAccountID(v *int64) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountNodeHealthUpdate) AddAccountID(v int64) *AccountNodeHealthUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *AccountNodeHealthUpdate) SetProxyID(v int64) *AccountNodeHealthUpdate {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableProxyID(v *int64) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *AccountNodeHealthUpdate) AddProxyID(v int64) *AccountNodeHealthUpdate {
	_u.mutation.AddProxyID(v)
	return _u
}

// SetRegion sets the "region" field.
func (_u *AccountNodeHealthUpdate) SetRegion(v string) *AccountNodeHealthUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableRegion(v *string) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *AccountNodeHealthUpdate) SetState(v string) *AccountNodeHealthUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableState(v *string) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetWindowOpenedAt sets the "window_opened_at" field.
func (_u *AccountNodeHealthUpdate) SetWindowOpenedAt(v time.Time) *AccountNodeHealthUpdate {
	_u.mutation.SetWindowOpenedAt(v)
	return _u
}

// SetNillableWindowOpenedAt sets the "window_opened_at" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableWindowOpenedAt(v *time.Time) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetWindowOpenedAt(*v)
	}
	return _u
}

// ClearWindowOpenedAt clears the value of the "window_opened_at" field.
func (_u *AccountNodeHealthUpdate) ClearWindowOpenedAt() *AccountNodeHealthUpdate {
	_u.mutation.ClearWindowOpenedAt()
	return _u
}

// SetDegradedAt sets the "degraded_at" field.
func (_u *AccountNodeHealthUpdate) SetDegradedAt(v time.Time) *AccountNodeHealthUpdate {
	_u.mutation.SetDegradedAt(v)
	return _u
}

// SetNillableDegradedAt sets the "degraded_at" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableDegradedAt(v *time.Time) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetDegradedAt(*v)
	}
	return _u
}

// ClearDegradedAt clears the value of the "degraded_at" field.
func (_u *AccountNodeHealthUpdate) ClearDegradedAt() *AccountNodeHealthUpdate {
	_u.mutation.ClearDegradedAt()
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *AccountNodeHealthUpdate) SetCooldownUntil(v time.Time) *AccountNodeHealthUpdate {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableCooldownUntil(v *time.Time) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *AccountNodeHealthUpdate) ClearCooldownUntil() *AccountNodeHealthUpdate {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetProbeCount sets the "probe_count" field.
func (_u *AccountNodeHealthUpdate) SetProbeCount(v int64) *AccountNodeHealthUpdate {
	_u.mutation.ResetProbeCount()
	_u.mutation.SetProbeCount(v)
	return _u
}

// SetNillableProbeCount sets the "probe_count" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableProbeCount(v *int64) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetProbeCount(*v)
	}
	return _u
}

// AddProbeCount adds value to the "probe_count" field.
func (_u *AccountNodeHealthUpdate) AddProbeCount(v int64) *AccountNodeHealthUpdate {
	_u.mutation.AddProbeCount(v)
	return _u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_u *AccountNodeHealthUpdate) SetLastProbeAt(v time.Time) *AccountNodeHealthUpdate {
	_u.mutation.SetLastProbeAt(v)
	return _u
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableLastProbeAt(v *time.Time) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetLastProbeAt(*v)
	}
	return _u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (_u *AccountNodeHealthUpdate) ClearLastProbeAt() *AccountNodeHealthUpdate {
	_u.mutation.ClearLastProbeAt()
	return _u
}

// SetLastProbeAnswer sets the "last_probe_answer" field.
func (_u *AccountNodeHealthUpdate) SetLastProbeAnswer(v string) *AccountNodeHealthUpdate {
	_u.mutation.SetLastProbeAnswer(v)
	return _u
}

// SetNillableLastProbeAnswer sets the "last_probe_answer" field if the given value is not nil.
func (_u *AccountNodeHealthUpdate) SetNillableLastProbeAnswer(v *string) *AccountNodeHealthUpdate {
	if v != nil {
		_u.SetLastProbeAnswer(*v)
	}
	return _u
}

// Mutation returns the AccountNodeHealthMutation object of the builder.
func (_u *AccountNodeHealthUpdate) Mutation() *AccountNodeHealthMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountNodeHealthUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountNodeHealthUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountNodeHealthUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountNodeHealthUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountNodeHealthUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountnodehealth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountNodeHealthUpdate) check() error {
	if v, ok := _u.mutation.Region(); ok {
		if err := accountnodehealth.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "AccountNodeHealth.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := accountnodehealth.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "AccountNodeHealth.state": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountNodeHealthUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountnodehealth.Table, accountnodehealth.Columns, sqlgraph.NewFieldSpec(accountnodehealth.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountnodehealth.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountnodehealth.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountnodehealth.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(accountnodehealth.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(accountnodehealth.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(accountnodehealth.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(accountnodehealth.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowOpenedAt(); ok {
		_spec.SetField(accountnodehealth.FieldWindowOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.WindowOpenedAtCleared() {
		_spec.ClearField(accountnodehealth.FieldWindowOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DegradedAt(); ok {
		_spec.SetField(accountnodehealth.FieldDegradedAt, field.TypeTime, value)
	}
	if _u.mutation.DegradedAtCleared() {
		_spec.ClearField(accountnodehealth.FieldDegradedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(accountnodehealth.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(accountnodehealth.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ProbeCount(); ok {
		_spec.SetField(accountnodehealth.FieldProbeCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProbeCount(); ok {
		_spec.AddField(accountnodehealth.FieldProbeCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastProbeAt(); ok {
		_spec.SetField(accountnodehealth.FieldLastProbeAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbeAtCleared() {
		_spec.ClearField(accountnodehealth.FieldLastProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProbeAnswer(); ok {
		_spec.SetField(accountnodehealth.FieldLastProbeAnswer, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountnodehealth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountNodeHealthUpdateOne is the builder for updating a single AccountNodeHealth entity.
type AccountNodeHealthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountNodeHealthMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountNodeHealthUpdateOne) SetUpdatedAt(v time.Time) *AccountNodeHealthUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountNodeHealthUpdateOne) SetAccountID(v int64) *AccountNodeHealthUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableAccountID(v *int64) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountNodeHealthUpdateOne) AddAccountID(v int64) *AccountNodeHealthUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *AccountNodeHealthUpdateOne) SetProxyID(v int64) *AccountNodeHealthUpdateOne {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableProxyID(v *int64) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *AccountNodeHealthUpdateOne) AddProxyID(v int64) *AccountNodeHealthUpdateOne {
	_u.mutation.AddProxyID(v)
	return _u
}

// SetRegion sets the "region" field.
func (_u *AccountNodeHealthUpdateOne) SetRegion(v string) *AccountNodeHealthUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableRegion(v *string) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *AccountNodeHealthUpdateOne) SetState(v string) *AccountNodeHealthUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableState(v *string) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetWindowOpenedAt sets the "window_opened_at" field.
func (_u *AccountNodeHealthUpdateOne) SetWindowOpenedAt(v time.Time) *AccountNodeHealthUpdateOne {
	_u.mutation.SetWindowOpenedAt(v)
	return _u
}

// SetNillableWindowOpenedAt sets the "window_opened_at" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableWindowOpenedAt(v *time.Time) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetWindowOpenedAt(*v)
	}
	return _u
}

// ClearWindowOpenedAt clears the value of the "window_opened_at" field.
func (_u *AccountNodeHealthUpdateOne) ClearWindowOpenedAt() *AccountNodeHealthUpdateOne {
	_u.mutation.ClearWindowOpenedAt()
	return _u
}

// SetDegradedAt sets the "degraded_at" field.
func (_u *AccountNodeHealthUpdateOne) SetDegradedAt(v time.Time) *AccountNodeHealthUpdateOne {
	_u.mutation.SetDegradedAt(v)
	return _u
}

// SetNillableDegradedAt sets the "degraded_at" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableDegradedAt(v *time.Time) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetDegradedAt(*v)
	}
	return _u
}

// ClearDegradedAt clears the value of the "degraded_at" field.
func (_u *AccountNodeHealthUpdateOne) ClearDegradedAt() *AccountNodeHealthUpdateOne {
	_u.mutation.ClearDegradedAt()
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *AccountNodeHealthUpdateOne) SetCooldownUntil(v time.Time) *AccountNodeHealthUpdateOne {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableCooldownUntil(v *time.Time) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *AccountNodeHealthUpdateOne) ClearCooldownUntil() *AccountNodeHealthUpdateOne {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetProbeCount sets the "probe_count" field.
func (_u *AccountNodeHealthUpdateOne) SetProbeCount(v int64) *AccountNodeHealthUpdateOne {
	_u.mutation.ResetProbeCount()
	_u.mutation.SetProbeCount(v)
	return _u
}

// SetNillableProbeCount sets the "probe_count" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableProbeCount(v *int64) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetProbeCount(*v)
	}
	return _u
}

// AddProbeCount adds value to the "probe_count" field.
func (_u *AccountNodeHealthUpdateOne) AddProbeCount(v int64) *AccountNodeHealthUpdateOne {
	_u.mutation.AddProbeCount(v)
	return _u
}

// SetLastProbeAt sets the "last_probe_at" field.
func (_u *AccountNodeHealthUpdateOne) SetLastProbeAt(v time.Time) *AccountNodeHealthUpdateOne {
	_u.mutation.SetLastProbeAt(v)
	return _u
}

// SetNillableLastProbeAt sets the "last_probe_at" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableLastProbeAt(v *time.Time) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetLastProbeAt(*v)
	}
	return _u
}

// ClearLastProbeAt clears the value of the "last_probe_at" field.
func (_u *AccountNodeHealthUpdateOne) ClearLastProbeAt() *AccountNodeHealthUpdateOne {
	_u.mutation.ClearLastProbeAt()
	return _u
}

// SetLastProbeAnswer sets the "last_probe_answer" field.
func (_u *AccountNodeHealthUpdateOne) SetLastProbeAnswer(v string) *AccountNodeHealthUpdateOne {
	_u.mutation.SetLastProbeAnswer(v)
	return _u
}

// SetNillableLastProbeAnswer sets the "last_probe_answer" field if the given value is not nil.
func (_u *AccountNodeHealthUpdateOne) SetNillableLastProbeAnswer(v *string) *AccountNodeHealthUpdateOne {
	if v != nil {
		_u.SetLastProbeAnswer(*v)
	}
	return _u
}

// Mutation returns the AccountNodeHealthMutation object of the builder.
func (_u *AccountNodeHealthUpdateOne) Mutation() *AccountNodeHealthMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountNodeHealthUpdate builder.
func (_u *AccountNodeHealthUpdateOne) Where(ps ...predicate.AccountNodeHealth) *AccountNodeHealthUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountNodeHealthUpdateOne) Select(field string, fields ...string) *AccountNodeHealthUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountNodeHealth entity.
func (_u *AccountNodeHealthUpdateOne) Save(ctx context.Context) (*AccountNodeHealth, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountNodeHealthUpdateOne) SaveX(ctx context.Context) *AccountNodeHealth {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountNodeHealthUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountNodeHealthUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountNodeHealthUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountnodehealth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountNodeHealthUpdateOne) check() error {
	if v, ok := _u.mutation.Region(); ok {
		if err := accountnodehealth.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "AccountNodeHealth.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := accountnodehealth.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "AccountNodeHealth.state": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountNodeHealthUpdateOne) sqlSave(ctx context.Context) (_node *AccountNodeHealth, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountnodehealth.Table, accountnodehealth.Columns, sqlgraph.NewFieldSpec(accountnodehealth.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountNodeHealth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountnodehealth.FieldID)
		for _, f := range fields {
			if !accountnodehealth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountnodehealth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountnodehealth.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountnodehealth.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountnodehealth.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(accountnodehealth.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(accountnodehealth.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(accountnodehealth.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(accountnodehealth.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.WindowOpenedAt(); ok {
		_spec.SetField(accountnodehealth.FieldWindowOpenedAt, field.TypeTime, value)
	}
	if _u.mutation.WindowOpenedAtCleared() {
		_spec.ClearField(accountnodehealth.FieldWindowOpenedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DegradedAt(); ok {
		_spec.SetField(accountnodehealth.FieldDegradedAt, field.TypeTime, value)
	}
	if _u.mutation.DegradedAtCleared() {
		_spec.ClearField(accountnodehealth.FieldDegradedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(accountnodehealth.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(accountnodehealth.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ProbeCount(); ok {
		_spec.SetField(accountnodehealth.FieldProbeCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProbeCount(); ok {
		_spec.AddField(accountnodehealth.FieldProbeCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastProbeAt(); ok {
		_spec.SetField(accountnodehealth.FieldLastProbeAt, field.TypeTime, value)
	}
	if _u.mutation.LastProbeAtCleared() {
		_spec.ClearField(accountnodehealth.FieldLastProbeAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProbeAnswer(); ok {
		_spec.SetField(accountnodehealth.FieldLastProbeAnswer, field.TypeString, value)
	}
	_node = &AccountNodeHealth{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountnodehealth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
